version: '3.8'

services:
  postgres:
    image: postgres:alpine
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: confeature_test
    ports:
      - 5432:5432

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    restart: unless-stopped
