version: '3.8'

services:
  postgres:
    image: postgres:alpine
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: confeature_test
    ports:
      - 5432:5432
